# Primeira Imagem com Go Lang
FROM golang:latest AS BUILDER

# Define endereço do app
WORKDIR /app

# Copia fontes em GO
COPY . .

# Realiza o build dentro da imagem
RUN go build ./fullcycle.go

# define imagem base final
FROM scratch

# define endereço do app
WORKDIR /app

# move o binário do app fullcycle d
COPY --from=builder /app/fullcycle .

# # executa:
ENTRYPOINT [ "./fullcycle" ]
