FROM golang:latest

WORKDIR /app

ENTRYPOINT [ go build ./fullcycle.go

# define imagem base 
# FROM scratch

# # define endereço do app
# WORKDIR /app

# # move o binário do app fullcycle
# COPY ./fullcycle .

# # executa:
# ENTRYPOINT [ "./fullcycle" ]
