FROM golang:latest as GO

WORKDIR /app

COPY . .

RUN go build ./fullcycle.go

# define imagem base 
FROM scratch

# # define endereço do app
WORKDIR /app

# # move o binário do app fullcycle
# COPY ./fullcycle .

# # executa:
# ENTRYPOINT [ "./fullcycle" ]
