FROM golang:latest

WORKDIR /app

RUN ""

# define imagem base 
FROM scratch

# define endereço do app
WORKDIR /app

# move o binário do app fullcycle
COPY ./fullcycle .

# executa:
ENTRYPOINT [ "./fullcycle" ]
