# Primeira Imagem com Go Lang
FROM golang:latest AS BUILDER

# Define endereço do app
WORKDIR /app

# Copia fontes em GO
COPY . .

# 
RUN go build ./fullcycle.go

# define imagem base 
FROM scratch

# # define endereço do app
WORKDIR /app

# # move o binário do app fullcycle
COPY --from=builder /app/fullcycle .

# # executa:
ENTRYPOINT [ "./fullcycle" ]
